### PR TITLE
Feature improve skillz integration

### PR DESCRIPTION
**Pull request by heyx3**
@JamesMcMahon @aguirre-miriam

### CODE REVIEW

**Comment by heyx3** [comment]
Update: apparently, git can normally understand the text version of unity assets just fine. It just has a problem here because it's going from binary to text.

**Comment by JamesMcMahon** [comment]
It actually recognizes them in the diff for `.unity` files but not `.asset`. Not sure why but it is YAML either way.

**Comment by heyx3** [comment]
No, the reason it's displaying some of them is because they're new files for the repo -- as far as Git is concerned, they've always been text (they'd probably be broken if you looked at the actual commit that converted them).

**Comment by heyx3** [comment]
@JamesMcMahon  Just updated the readme

**Comment by JamesMcMahon** [comment]
LGTM. We can merge when the new release is going out.

**Pull request merged**
